/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.esprit.infob3.pidev.GUI;

import com.esprit.infob3.pidev.dao.impl.ClientDao;
import com.esprit.infob3.pidev.metier.ClientService;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class Achatparptfedilite extends javax.swing.JFrame {
public String pourcentage ;
    /**
     * Creates new form Achatparptfedilite
     */
    public Achatparptfedilite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 130, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 130, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Reduction 20%");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseEntered(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Reduction 40%");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Reduction 50%");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel1.setText("Numero :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 30));

        jLabel2.setText("Code :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, 20));

        jLabel3.setText("Reference :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 60, 20));

        jButton1.setText("Acheter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 80, 60));

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 100, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/infob3/pidev/GUI/shpping.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        setSize(new java.awt.Dimension(862, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (pourcentage.equals("reduction 20%"))
{ try 
        {
        String code = jTextField2.getText();
        String num =    jTextField1.getText();
        int numeroo = Integer.parseInt(num);
       int coda =Integer.parseInt(code);
        ClientService cs = new ClientService();
        ClientDao cdao = new ClientDao();
        int index = Paiement.jTable1.getSelectedRow();
        String login = ClientAuth.jTextField1.getText();
        TableModel model = Paiement.jTable1.getModel();
        String productid = model.getValueAt(index, 0).toString();
        int pdid = Integer.parseInt(productid);
        int reference = Integer.parseInt(jTextField3.getText());
        int idclient =cdao.findIdentifiant(login);
       
           
      
        cs.achatProduitSpeciale20(numeroo, coda, pdid,idclient,reference);
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(AchatNormal.class.getName()).log(Level.SEVERE, null, ex);
        }
}
else if (pourcentage.equals("reduction 40%"))
{
            String code = jTextField2.getText();
        String num =    jTextField1.getText();
        long numeroo = Long.parseLong(num);
       int coda =Integer.parseInt(code);
        ClientService cs = new ClientService();
        ClientDao cdao = new ClientDao();
        int index = Paiement.jTable1.getSelectedRow();
        String login = ClientAuth.jTextField1.getText();
        TableModel model = Paiement.jTable1.getModel();
        String productid = model.getValueAt(index, 0).toString();
        int pdid = Integer.parseInt(productid);
        int reference = Integer.parseInt(jTextField3.getText());
        
        try 
        {
           
       int idclient =cdao.findIdentifiant(login);
        cs.achatProduitSpeciale40(numeroo, coda, pdid,idclient,reference);
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(AchatNormal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                                                 
}
       else if(pourcentage.equals("reduction 50%"))
       {
         String code = jTextField2.getText();
        String num =    jTextField1.getText();
        long numeroo = Long.parseLong(num);
       int coda =Integer.parseInt(code);
        ClientService cs = new ClientService();
        ClientDao cdao = new ClientDao();
        int index = Paiement.jTable1.getSelectedRow();
        String login = ClientAuth.jTextField1.getText();
        TableModel model = Paiement.jTable1.getModel();
        String productid = model.getValueAt(index, 0).toString();
        int pdid = Integer.parseInt(productid);
        int reference = Integer.parseInt(jTextField3.getText());
        
        try 
        {
           
       int idclient =cdao.findIdentifiant(login);
        cs.achatProduitSpeciale50(numeroo, coda, pdid,idclient,reference);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(AchatNormal.class.getName()).log(Level.SEVERE, null, ex);
        }   
        }
       else { String code = jTextField2.getText();
        String num =    jTextField1.getText();
        long numeroo = Long.parseLong(num);
       int coda =Integer.parseInt(code);
        ClientService cs = new ClientService();
        ClientDao cdao = new ClientDao();
        int index = Paiement.jTable1.getSelectedRow();
        String login = ClientAuth.jTextField1.getText();
        TableModel model = Paiement.jTable1.getModel();
        String productid = model.getValueAt(index, 0).toString();
        int pdid = Integer.parseInt(productid);
        int reference = Integer.parseInt(jTextField3.getText());
        
        try 
        {
           
       int idclient =cdao.findIdentifiant(login);
        cs.achatProduitSpeciale(numeroo, coda, pdid,idclient,reference);
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(AchatNormal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseEntered
           pourcentage ="Reduction 20%";
    }//GEN-LAST:event_jRadioButton1MouseEntered

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
           pourcentage ="Reduction 40%";
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        pourcentage ="Reduction 50%";
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
       MenuClientFirst c = new MenuClientFirst();
       c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Achatparptfedilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Achatparptfedilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Achatparptfedilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Achatparptfedilite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Achatparptfedilite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
